variables:
   USERNAME: deployment
   SERVER_IP: 10.1.100.46

image: node:12

cache:
    paths:
    - node_modules/

stages:
   - build
   - deploy

### BUILDS

build:
  stage: build
  only:
    - dev

  script:
  - npm install
  - npm run compile
  - cp "$DEV_SERVER_CONFIG" dist/serverConfig.json
  artifacts:
    paths:
    - dist/
    - package.json
    
### DEPLOYMENTS

devDeploy:
  stage: deploy
  only:
    - dev
  script:
   - apt-get update -y
   - apt-get install openssh-client -y

   - eval $(ssh-agent -s)

   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh

   - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
   - chmod 644 ~/.ssh/known_hosts

   - chmod 600 "$DEV_PRIVATE_KEY"
   - ssh-add "$DEV_PRIVATE_KEY" > /dev/null

   - ssh -p22 $USERNAME@$SERVER_IP "rm -rf /srv/devNode/*"
   - scp -P22 -r dist $USERNAME@$SERVER_IP:/srv/devNode/
   - scp -P22 -r package.json $USERNAME@$SERVER_IP:/srv/devNode/
   - ssh -p22 $USERNAME@$SERVER_IP "cd /srv/devNode && npm install --production"
   - ssh -p22 $USERNAME@$SERVER_IP "date > /srv/devNodeUpdated"
