variables:
   USERNAME: deployment
   SERVER_IP: 10.1.100.46

image: node:11

cache:
    paths:
    - app/node_modules/

stages:
   - build
   - deploy

### BUILDS

build:
  stage: build
  only:
    - dev

  script:
  - npm install
  - npm run lint
  - npm run build
  artifacts:
    paths:
    - main.js
    
### DEPLOYMENTS

devDeploy:
  stage: deploy
  only:
    - dev
  script:
   - apt-get update -y
   - apt-get install openssh-client -y

   - eval $(ssh-agent -s)

   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh

   - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
   - chmod 644 ~/.ssh/known_hosts

   - echo "$DEV_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

   - ssh -p22 $USERNAME@$SERVER_IP "rm -rf /srv/devNode/*"
   - scp -P22 -r main.js $USERNAME@$SERVER_IP:/srv/devNode/main.js
