version: '3'
services:
  pebl-services:
    image: git.eduworks.us:5050/pebl/pebl-services/services:1.0.16
    ports:
      - "443:443"
    restart: always
    environment:
      - SERVER_NAME=localhost
      - CONSUMING_DOMAIN=*
      - AUTH_PROVIDER_URL=https://dev.keycloak.eduworks.com/auth/realms/master
      - AUTH_CLIENT_SECRET=
      - AUTH_CLIENT_ID=PeBL-Services
      - SERVER_AUTH_REDIRECT_URL=https://localhost/redirect
      - AUTH_RESPONSE_TYPES=code
      - AUTH_SCOPE=openid email profile
      - POSTGRES_SQL_URL=postgres://pebl:Tacotrucked@pg:5432/services
      - AUTH_METHOD=openid
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_AUTH=testing
      - SESSION_SECRET=<sessionSecret>
      - SERVER_PORT=443
      - USE_SSL=true
      - LRS_URL=https://lrs.peblproject.com/data/xapi
      - LRS_BASIC_AUTH=<basic token>
#    volumes:
#      - /etc/letsencrypt/live/<site>/fullchain.pem:/ssl/fullchain.pem
#      - /etc/letsencrypt/live/<site>/privkey.pem:/ssl/privkey.pem

  redis:
    image: git.eduworks.us:5050/pebl/pebl-services/ssh-tunnel:1.0.0
    restart: always
    volumes:
      - /home/veden/Desktop/taco:/ssl/privkey.pem
    command: ["./setupTunnel.sh", "taco", "34.222.38.192", "6379"]

  pg:
    image: git.eduworks.us:5050/pebl/pebl-services/ssh-tunnel:1.0.0
    restart: always
    volumes:
      - /home/veden/Desktop/taco:/ssl/privkey.pem
    command: ["./setupTunnel.sh", "taco", "34.222.38.192", "5432"]
