version: '3'
services:
  ssh-tunnel:
    image: ssh-tunnel:1.0.0
    build:
      context: .
      dockerfile: DockerfileTunnel
    restart: always
    volumes:
      - /home/veden/Desktop/taco:/ssl/redis.pem
    command: ["./setupTunnel.sh", "taco", "/ssl/redis.pem", "34.222.38.192", "6379"]
